PACKAGE = irc-example
PACKAGE_ID = $(PACKAGE)@patrick.cloke
PACKAGE_NAME = IRC Example
PACKAGE_VERSION = 1.0
PACKAGE_DESCRIPTION = Example IRC for running a command after connecting an account.
PACKAGE_AUTHOR = Patrick Cloke
PACKAGE_MIN_VERSION = 1.2a1pre
PACKAGE_MAX_VERSION = 1.2

include ../rules.mk
