PACKAGE = irc-ignore
PACKAGE_ID = $(PACKAGE)@patrick.cloke
PACKAGE_NAME = IRC ignore
PACKAGE_VERSION = 0.1
PACKAGE_DESCRIPTION = Add an ignore command to IRC.
PACKAGE_AUTHOR = Patrick Cloke
PACKAGE_MIN_VERSION = 1.4
PACKAGE_MAX_VERSION = 1.5a1pre

include ../rules.mk
