PACKAGE = irc-stats
PACKAGE_ID = $(PACKAGE)@patrick.cloke
PACKAGE_NAME = IRC stats
PACKAGE_VERSION = 0.1
PACKAGE_DESCRIPTION = Keep track of some stats of other users on IRC.
PACKAGE_AUTHOR = Patrick Cloke
PACKAGE_MIN_VERSION = 1.6a1pre
PACKAGE_MAX_VERSION = 1.6a1pre

include ../rules.mk
