PACKAGE = irc-extras
PACKAGE_ID = $(PACKAGE)@patrick.cloke
PACKAGE_NAME = IRC Extras
PACKAGE_VERSION = 1.0
PACKAGE_DESCRIPTION = Handle extra IRC messages Instantbird ignores.
PACKAGE_AUTHOR = Patrick Cloke
PACKAGE_MIN_VERSION = 1.2a1pre
PACKAGE_MAX_VERSION = 1.2

include ../rules.mk
